[project]
name = "sendgrid_nodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sendgrid",
]

[tool.uv.sources]
griptape-nodes-engine = { git = "https://github.com/griptape-ai/griptape-nodes-engine", rev="latest"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

